fix: Fix RBAC test crashing because of `null` IDs
If the IDs are null, when the query compares the IDs, an exception occurs:
java.lang.RuntimeException: Error evaluating constraint 'id == roleId' in []

So, we have to set the IDs manually when testing. Or just create a ctor with id params.